version: "3"
services:
  EmployeeManagement:
    image: EmployeeManagement
    user: root
    depends_on:
      - postgres
    volumes:
      - jmix:/workspace/.jmix
    environment:
      - MAIN_DATASOURCE_URL=jdbc:postgresql://postgres/employee_management
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee_management
volumes:
  jmix:
  postgres: